### ISSUE TITLE
apply drymass on each folder in a main folder

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#15]
Currently, I'm acquiring phase data of drops for20s/~70frames per drop. It is kind of pain to apply for each time manually "dm_analyze_sphere.exe "main_folder\folder_name\folder_name.zip" ".

**Comment by paulmueller** [comment]
TODO:
- [ ] support case when a directory containing measurements without any subdirectory is given (currently only works without -r command-line parameter)
- [ ] write test functions

**Comment by gcojoc** [comment]
Hi Paul,

For some reason github does not work very well this morning, so I send an email.

I installed drymass 0.7.1, but I get an error when run it in the ‘case when a directory containing measurements without any subdirectory is given’ (please see the attachment).

Best,
Geo.
