### ISSUE TITLE
drymass on objects that have an elliptical equatorial cross-section 

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#16]
major and minor radius 
volume computed by a rotational symmetry

**Comment by gcojoc** [comment]
ok, I'll check it. thanks

**Comment by gcojoc** [comment]
![error on dm_analyze_stretch](https://user-images.githubusercontent.com/34100125/47091123-89f52480-d224-11e8-8ff7-3c5f30517d97.jpg)

got this error

**Comment by paulmueller** [comment]
I think you are using an outdated version of qpstretch. Please update the SVN repository "d:\\02. kits and utilities\qpi" using TortoiseSVN. You should have at least revision 47.

**Comment by gcojoc** [comment]
The update of SVN repository resolved the issue. Thanks.

**Comment by gcojoc** [comment]
but there are differences in the computed RI. 
![figure_1](https://user-images.githubusercontent.com/34100125/47140435-7e563c00-d2be-11e8-8cd0-b2e217d3831f.png)
