### ISSUE TITLE
sphere and stretch analysis yield different RI values

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#17]
![figure_1](https://user-images.githubusercontent.com/34100125/47140435-7e563c00-d2be-11e8-8cd0-b2e217d3831f.png)

_Originally posted by @gcojoc in https://github.com/RI-imaging/DryMass/issue_comments#issuecomment-430917055_

**Comment by paulmueller** [comment]
Which method are you using for the sphere analysis, i.e. "method" and "model" keys in the [sphere] section of drymass.cfg?

**Comment by gcojoc** [comment]
Edge projection. I did not have time to run a image rytov-sc. Would 'image rytov-sc' give, for sphere, similar results with stretch?

**Comment by paulmueller** [comment]
It depends on the data, but yes, "edge projection" overestimates the RI.

**Comment by gcojoc** [comment]
I'm running now 'image rytov-sc'  and the RI for the first frames is similar with what I got running 'stretch'.
Thanks.
