### ISSUE TITLE
phase line plot does not show negative phase values

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#18]
No sure why, but I do not get negative values, for the phase line plot, at the edge of the drop. Any idea?  
![sphere_edge_projection_images](https://user-images.githubusercontent.com/34100125/47152790-f718c080-d2dd-11e8-9489-8f859e63dd0a.jpg)

**Comment by paulmueller** [comment]
I dp not see a reason why there should be negative phase values. The data (phase) image only has minor negative phase values at the corners of the image.

**Comment by gcojoc** [comment]
Puzzled. I thought you said that should be always the case.

**Comment by paulmueller** [comment]
Ok sorry. But then this is not related to DryMass and should be discussed in the Optics Meeting.
