### ISSUE TITLE
dm_analyze_stretch not working in recursive mode

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#21]
dm_analyze_stretch.exe (edge projection) does not work recursively like dm_analyze_sphere.exe (edge projection or image rytov-sc) does.

**Comment by paulmueller** [comment]
Please update the SVN repository and make sure you are at least at revision 66.

**Comment by gcojoc** [comment]
After the update recursive dm_analyze_stretch.exe works.
