### ISSUE TITLE
No time and dry_mass info for dm_analyze_stretch.exe

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#22]
*statistics.txt files do not contain the time and dry_mass information. Is there any specific reason to not have it? If not, for further analysis, would be good to have it in these files too.

**Comment by paulmueller** [comment]
In dm_analyze_sphere, the dry mas is computed from all values within a circle of a given radius. If we do something similar in dm_analyze_stretch, then the computed dry mass might be slightly different from that given by dm_analyze_sphere. I think this might be confusing for the user, so I would rather not implement it.

However, you can still combine the analysis results from dm_analyze_sphere and dm_analyze_stretch. The analysis order is the same. 

I don't see a problem with adding the time information.

**Comment by paulmueller** [comment]
Update: time info is now implemented in qpstretch

**Comment by paulmueller** [comment]
@gcojoc Is this still an issue?

**Comment by gcojoc** [comment]
No, not anymore.
