### ISSUE TITLE
stretch analysis on stack - chrashes when a frame can't be analysed  

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#26]
There are cases of  stack/serie of imagines in which not all the frames have an object to be analyzed. When performing stretch mode analysis, the software will stop analyzing that stack  (and any other recurent stack) and not save the images analyzed, although the computed data is printed in the xx_statistics file.

**Comment by paulmueller** [comment]
Could you please point me to an example dataset?

**Comment by gcojoc** [comment]
y:\XX_GENERAL_USE\data_FUS\01_RI_data_FUS\534_check\

**Comment by paulmueller** [comment]
The problem was that an array index was rounded from a floating point value to an integer that was outside of the array shape. It is fixed now in revision 70.
